/*
 * generated by Xtext 2.41.0
 */
package org.example.quiz;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QuizDSLStandaloneSetup extends QuizDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new QuizDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
