/*
 * generated by Xtext 2.41.0
 */
package org.example.quiz.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class QuizDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class QuizGameSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.QuizGameSystem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cThemesAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cThemesThemeParserRuleCall_0_0 = (RuleCall)cThemesAssignment_0.eContents().get(0);
		private final Assignment cUsersAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cUsersUserParserRuleCall_1_0 = (RuleCall)cUsersAssignment_1.eContents().get(0);
		private final Assignment cPlatformAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cPlatformQuizPlatformParserRuleCall_2_0 = (RuleCall)cPlatformAssignment_2.eContents().get(0);
		private final Assignment cResultsAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cResultsQuizResultParserRuleCall_3_0 = (RuleCall)cResultsAssignment_3.eContents().get(0);
		
		//QuizGameSystem:
		//    (themes+=Theme | users+=User | platform=QuizPlatform | results+=QuizResult)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(themes+=Theme | users+=User | platform=QuizPlatform | results+=QuizResult)*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//themes+=Theme
		public Assignment getThemesAssignment_0() { return cThemesAssignment_0; }
		
		//Theme
		public RuleCall getThemesThemeParserRuleCall_0_0() { return cThemesThemeParserRuleCall_0_0; }
		
		//users+=User
		public Assignment getUsersAssignment_1() { return cUsersAssignment_1; }
		
		//User
		public RuleCall getUsersUserParserRuleCall_1_0() { return cUsersUserParserRuleCall_1_0; }
		
		//platform=QuizPlatform
		public Assignment getPlatformAssignment_2() { return cPlatformAssignment_2; }
		
		//QuizPlatform
		public RuleCall getPlatformQuizPlatformParserRuleCall_2_0() { return cPlatformQuizPlatformParserRuleCall_2_0; }
		
		//results+=QuizResult
		public Assignment getResultsAssignment_3() { return cResultsAssignment_3; }
		
		//QuizResult
		public RuleCall getResultsQuizResultParserRuleCall_3_0() { return cResultsQuizResultParserRuleCall_3_0; }
	}
	public class ThemeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.Theme");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cThemeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cPrimaryKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPrimaryColorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrimaryColorSTRINGTerminalRuleCall_3_0 = (RuleCall)cPrimaryColorAssignment_3.eContents().get(0);
		private final Keyword cSecondaryKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSecondaryColorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSecondaryColorSTRINGTerminalRuleCall_5_0 = (RuleCall)cSecondaryColorAssignment_5.eContents().get(0);
		private final Keyword cBgKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBackgroundColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cBackgroundColorSTRINGTerminalRuleCall_7_0 = (RuleCall)cBackgroundColorAssignment_7.eContents().get(0);
		private final Keyword cTextKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTextColorAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTextColorSTRINGTerminalRuleCall_9_0 = (RuleCall)cTextColorAssignment_9.eContents().get(0);
		private final Keyword cFontKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cFontNameAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cFontNameSTRINGTerminalRuleCall_11_0 = (RuleCall)cFontNameAssignment_11.eContents().get(0);
		private final Keyword cEndKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Theme:
		//    'theme' name=ID
		//        'primary' primaryColor=STRING
		//        'secondary' secondaryColor=STRING
		//        'bg' backgroundColor=STRING
		//        'text' textColor=STRING
		//        'font' fontName=STRING
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'theme' name=ID
		//    'primary' primaryColor=STRING
		//    'secondary' secondaryColor=STRING
		//    'bg' backgroundColor=STRING
		//    'text' textColor=STRING
		//    'font' fontName=STRING
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'theme'
		public Keyword getThemeKeyword_0() { return cThemeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'primary'
		public Keyword getPrimaryKeyword_2() { return cPrimaryKeyword_2; }
		
		//primaryColor=STRING
		public Assignment getPrimaryColorAssignment_3() { return cPrimaryColorAssignment_3; }
		
		//STRING
		public RuleCall getPrimaryColorSTRINGTerminalRuleCall_3_0() { return cPrimaryColorSTRINGTerminalRuleCall_3_0; }
		
		//'secondary'
		public Keyword getSecondaryKeyword_4() { return cSecondaryKeyword_4; }
		
		//secondaryColor=STRING
		public Assignment getSecondaryColorAssignment_5() { return cSecondaryColorAssignment_5; }
		
		//STRING
		public RuleCall getSecondaryColorSTRINGTerminalRuleCall_5_0() { return cSecondaryColorSTRINGTerminalRuleCall_5_0; }
		
		//'bg'
		public Keyword getBgKeyword_6() { return cBgKeyword_6; }
		
		//backgroundColor=STRING
		public Assignment getBackgroundColorAssignment_7() { return cBackgroundColorAssignment_7; }
		
		//STRING
		public RuleCall getBackgroundColorSTRINGTerminalRuleCall_7_0() { return cBackgroundColorSTRINGTerminalRuleCall_7_0; }
		
		//'text'
		public Keyword getTextKeyword_8() { return cTextKeyword_8; }
		
		//textColor=STRING
		public Assignment getTextColorAssignment_9() { return cTextColorAssignment_9; }
		
		//STRING
		public RuleCall getTextColorSTRINGTerminalRuleCall_9_0() { return cTextColorSTRINGTerminalRuleCall_9_0; }
		
		//'font'
		public Keyword getFontKeyword_10() { return cFontKeyword_10; }
		
		//fontName=STRING
		public Assignment getFontNameAssignment_11() { return cFontNameAssignment_11; }
		
		//STRING
		public RuleCall getFontNameSTRINGTerminalRuleCall_11_0() { return cFontNameSTRINGTerminalRuleCall_11_0; }
		
		//'end'
		public Keyword getEndKeyword_12() { return cEndKeyword_12; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cUidKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUsernameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUsernameSTRINGTerminalRuleCall_3_0 = (RuleCall)cUsernameAssignment_3.eContents().get(0);
		private final Keyword cPwdKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPasswordAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPasswordSTRINGTerminalRuleCall_5_0 = (RuleCall)cPasswordAssignment_5.eContents().get(0);
		private final Keyword cNameKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFullNameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFullNameSTRINGTerminalRuleCall_7_0 = (RuleCall)cFullNameAssignment_7.eContents().get(0);
		private final Assignment cRoleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRoleUserRoleEnumRuleCall_8_0 = (RuleCall)cRoleAssignment_8.eContents().get(0);
		private final Keyword cEndKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//User:
		//    'user' name=ID
		//        'uid' username=STRING
		//        'pwd' password=STRING
		//        'name' fullName=STRING
		//        (role=UserRole)?
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'user' name=ID
		//    'uid' username=STRING
		//    'pwd' password=STRING
		//    'name' fullName=STRING
		//    (role=UserRole)?
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'user'
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'uid'
		public Keyword getUidKeyword_2() { return cUidKeyword_2; }
		
		//username=STRING
		public Assignment getUsernameAssignment_3() { return cUsernameAssignment_3; }
		
		//STRING
		public RuleCall getUsernameSTRINGTerminalRuleCall_3_0() { return cUsernameSTRINGTerminalRuleCall_3_0; }
		
		//'pwd'
		public Keyword getPwdKeyword_4() { return cPwdKeyword_4; }
		
		//password=STRING
		public Assignment getPasswordAssignment_5() { return cPasswordAssignment_5; }
		
		//STRING
		public RuleCall getPasswordSTRINGTerminalRuleCall_5_0() { return cPasswordSTRINGTerminalRuleCall_5_0; }
		
		//'name'
		public Keyword getNameKeyword_6() { return cNameKeyword_6; }
		
		//fullName=STRING
		public Assignment getFullNameAssignment_7() { return cFullNameAssignment_7; }
		
		//STRING
		public RuleCall getFullNameSTRINGTerminalRuleCall_7_0() { return cFullNameSTRINGTerminalRuleCall_7_0; }
		
		//(role=UserRole)?
		public Assignment getRoleAssignment_8() { return cRoleAssignment_8; }
		
		//UserRole
		public RuleCall getRoleUserRoleEnumRuleCall_8_0() { return cRoleUserRoleEnumRuleCall_8_0; }
		
		//'end'
		public Keyword getEndKeyword_9() { return cEndKeyword_9; }
	}
	public class QuizPlatformElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.QuizPlatform");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlatformKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTitleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTitleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTitleSTRINGTerminalRuleCall_3_0 = (RuleCall)cTitleAssignment_3.eContents().get(0);
		private final Keyword cSubtitleKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSubtitleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSubtitleSTRINGTerminalRuleCall_5_0 = (RuleCall)cSubtitleAssignment_5.eContents().get(0);
		private final Keyword cLogoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLogoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLogoSTRINGTerminalRuleCall_7_0 = (RuleCall)cLogoAssignment_7.eContents().get(0);
		private final Keyword cUse_themeKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cThemeAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cThemeThemeCrossReference_9_0 = (CrossReference)cThemeAssignment_9.eContents().get(0);
		private final RuleCall cThemeThemeIDTerminalRuleCall_9_0_1 = (RuleCall)cThemeThemeCrossReference_9_0.eContents().get(1);
		private final Assignment cQuizzesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cQuizzesQuizParserRuleCall_10_0 = (RuleCall)cQuizzesAssignment_10.eContents().get(0);
		private final Keyword cEndKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//QuizPlatform:
		//    'platform' name=ID
		//        'title' title=STRING
		//        'subtitle' subtitle=STRING
		//        'logo' logo=STRING
		//        'use_theme' theme=[Theme]
		//        quizzes+=Quiz*
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'platform' name=ID
		//    'title' title=STRING
		//    'subtitle' subtitle=STRING
		//    'logo' logo=STRING
		//    'use_theme' theme=[Theme]
		//    quizzes+=Quiz*
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'platform'
		public Keyword getPlatformKeyword_0() { return cPlatformKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'title'
		public Keyword getTitleKeyword_2() { return cTitleKeyword_2; }
		
		//title=STRING
		public Assignment getTitleAssignment_3() { return cTitleAssignment_3; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_3_0() { return cTitleSTRINGTerminalRuleCall_3_0; }
		
		//'subtitle'
		public Keyword getSubtitleKeyword_4() { return cSubtitleKeyword_4; }
		
		//subtitle=STRING
		public Assignment getSubtitleAssignment_5() { return cSubtitleAssignment_5; }
		
		//STRING
		public RuleCall getSubtitleSTRINGTerminalRuleCall_5_0() { return cSubtitleSTRINGTerminalRuleCall_5_0; }
		
		//'logo'
		public Keyword getLogoKeyword_6() { return cLogoKeyword_6; }
		
		//logo=STRING
		public Assignment getLogoAssignment_7() { return cLogoAssignment_7; }
		
		//STRING
		public RuleCall getLogoSTRINGTerminalRuleCall_7_0() { return cLogoSTRINGTerminalRuleCall_7_0; }
		
		//'use_theme'
		public Keyword getUse_themeKeyword_8() { return cUse_themeKeyword_8; }
		
		//theme=[Theme]
		public Assignment getThemeAssignment_9() { return cThemeAssignment_9; }
		
		//[Theme]
		public CrossReference getThemeThemeCrossReference_9_0() { return cThemeThemeCrossReference_9_0; }
		
		//ID
		public RuleCall getThemeThemeIDTerminalRuleCall_9_0_1() { return cThemeThemeIDTerminalRuleCall_9_0_1; }
		
		//quizzes+=Quiz*
		public Assignment getQuizzesAssignment_10() { return cQuizzesAssignment_10; }
		
		//Quiz
		public RuleCall getQuizzesQuizParserRuleCall_10_0() { return cQuizzesQuizParserRuleCall_10_0; }
		
		//'end'
		public Keyword getEndKeyword_11() { return cEndKeyword_11; }
	}
	public class QuizElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.Quiz");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuizKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLabelKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLabelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLabelSTRINGTerminalRuleCall_3_0 = (RuleCall)cLabelAssignment_3.eContents().get(0);
		private final Keyword cDescKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescriptionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescriptionAssignment_5.eContents().get(0);
		private final Keyword cIconKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIconAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIconSTRINGTerminalRuleCall_7_0 = (RuleCall)cIconAssignment_7.eContents().get(0);
		private final Assignment cConfigAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cConfigQuizConfigParserRuleCall_8_0 = (RuleCall)cConfigAssignment_8.eContents().get(0);
		private final Assignment cQuestionsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cQuestionsQuestionParserRuleCall_9_0 = (RuleCall)cQuestionsAssignment_9.eContents().get(0);
		private final Keyword cEndKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Quiz:
		//    'quiz' name=ID
		//        'label' label=STRING
		//        'desc' description=STRING
		//        'icon' icon=STRING
		//        config=QuizConfig
		//        questions+=Question*
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'quiz' name=ID
		//    'label' label=STRING
		//    'desc' description=STRING
		//    'icon' icon=STRING
		//    config=QuizConfig
		//    questions+=Question*
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'quiz'
		public Keyword getQuizKeyword_0() { return cQuizKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'label'
		public Keyword getLabelKeyword_2() { return cLabelKeyword_2; }
		
		//label=STRING
		public Assignment getLabelAssignment_3() { return cLabelAssignment_3; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_3_0() { return cLabelSTRINGTerminalRuleCall_3_0; }
		
		//'desc'
		public Keyword getDescKeyword_4() { return cDescKeyword_4; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_5() { return cDescriptionAssignment_5; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_0() { return cDescriptionSTRINGTerminalRuleCall_5_0; }
		
		//'icon'
		public Keyword getIconKeyword_6() { return cIconKeyword_6; }
		
		//icon=STRING
		public Assignment getIconAssignment_7() { return cIconAssignment_7; }
		
		//STRING
		public RuleCall getIconSTRINGTerminalRuleCall_7_0() { return cIconSTRINGTerminalRuleCall_7_0; }
		
		//config=QuizConfig
		public Assignment getConfigAssignment_8() { return cConfigAssignment_8; }
		
		//QuizConfig
		public RuleCall getConfigQuizConfigParserRuleCall_8_0() { return cConfigQuizConfigParserRuleCall_8_0; }
		
		//questions+=Question*
		public Assignment getQuestionsAssignment_9() { return cQuestionsAssignment_9; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_9_0() { return cQuestionsQuestionParserRuleCall_9_0; }
		
		//'end'
		public Keyword getEndKeyword_10() { return cEndKeyword_10; }
	}
	public class QuizConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.QuizConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQuizConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAccessAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAccessAccessTypeEnumRuleCall_1_0 = (RuleCall)cAccessAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTimeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDurationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDurationINTTerminalRuleCall_2_1_0 = (RuleCall)cDurationAssignment_2_1.eContents().get(0);
		private final Keyword cMinKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStartKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStartTimeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStartTimeSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cStartTimeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEndKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEndTimeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEndTimeSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cEndTimeAssignment_4_1.eContents().get(0);
		private final Assignment cShuffleQuestionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cShuffleQuestionsShuffleKeyword_5_0 = (Keyword)cShuffleQuestionsAssignment_5.eContents().get(0);
		private final Assignment cShowResultAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cShowResultShow_resultKeyword_6_0 = (Keyword)cShowResultAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cScoreKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTotalScoreAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTotalScoreINTTerminalRuleCall_7_1_0 = (RuleCall)cTotalScoreAssignment_7_1.eContents().get(0);
		
		//QuizConfig:
		//    {QuizConfig}
		//    (access=AccessType)
		//    ('time' duration=INT 'min')?
		//    ('start' startTime=STRING)?
		//    ('end' endTime=STRING)?
		//    (shuffleQuestions?='shuffle')?
		//    (showResult?='show_result')?
		//    ('score' totalScore=INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{QuizConfig}
		//(access=AccessType)
		//('time' duration=INT 'min')?
		//('start' startTime=STRING)?
		//('end' endTime=STRING)?
		//(shuffleQuestions?='shuffle')?
		//(showResult?='show_result')?
		//('score' totalScore=INT)?
		public Group getGroup() { return cGroup; }
		
		//{QuizConfig}
		public Action getQuizConfigAction_0() { return cQuizConfigAction_0; }
		
		//(access=AccessType)
		public Assignment getAccessAssignment_1() { return cAccessAssignment_1; }
		
		//AccessType
		public RuleCall getAccessAccessTypeEnumRuleCall_1_0() { return cAccessAccessTypeEnumRuleCall_1_0; }
		
		//('time' duration=INT 'min')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'time'
		public Keyword getTimeKeyword_2_0() { return cTimeKeyword_2_0; }
		
		//duration=INT
		public Assignment getDurationAssignment_2_1() { return cDurationAssignment_2_1; }
		
		//INT
		public RuleCall getDurationINTTerminalRuleCall_2_1_0() { return cDurationINTTerminalRuleCall_2_1_0; }
		
		//'min'
		public Keyword getMinKeyword_2_2() { return cMinKeyword_2_2; }
		
		//('start' startTime=STRING)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'start'
		public Keyword getStartKeyword_3_0() { return cStartKeyword_3_0; }
		
		//startTime=STRING
		public Assignment getStartTimeAssignment_3_1() { return cStartTimeAssignment_3_1; }
		
		//STRING
		public RuleCall getStartTimeSTRINGTerminalRuleCall_3_1_0() { return cStartTimeSTRINGTerminalRuleCall_3_1_0; }
		
		//('end' endTime=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'end'
		public Keyword getEndKeyword_4_0() { return cEndKeyword_4_0; }
		
		//endTime=STRING
		public Assignment getEndTimeAssignment_4_1() { return cEndTimeAssignment_4_1; }
		
		//STRING
		public RuleCall getEndTimeSTRINGTerminalRuleCall_4_1_0() { return cEndTimeSTRINGTerminalRuleCall_4_1_0; }
		
		//(shuffleQuestions?='shuffle')?
		public Assignment getShuffleQuestionsAssignment_5() { return cShuffleQuestionsAssignment_5; }
		
		//'shuffle'
		public Keyword getShuffleQuestionsShuffleKeyword_5_0() { return cShuffleQuestionsShuffleKeyword_5_0; }
		
		//(showResult?='show_result')?
		public Assignment getShowResultAssignment_6() { return cShowResultAssignment_6; }
		
		//'show_result'
		public Keyword getShowResultShow_resultKeyword_6_0() { return cShowResultShow_resultKeyword_6_0; }
		
		//('score' totalScore=INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'score'
		public Keyword getScoreKeyword_7_0() { return cScoreKeyword_7_0; }
		
		//totalScore=INT
		public Assignment getTotalScoreAssignment_7_1() { return cTotalScoreAssignment_7_1; }
		
		//INT
		public RuleCall getTotalScoreINTTerminalRuleCall_7_1_0() { return cTotalScoreINTTerminalRuleCall_7_1_0; }
	}
	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSingleChoiceQuestionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultipleChoiceQuestionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTrueFalseQuestionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDescriptiveQuestionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Question:
		//    SingleChoiceQuestion | MultipleChoiceQuestion | TrueFalseQuestion | DescriptiveQuestion;
		@Override public ParserRule getRule() { return rule; }
		
		//SingleChoiceQuestion | MultipleChoiceQuestion | TrueFalseQuestion | DescriptiveQuestion
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SingleChoiceQuestion
		public RuleCall getSingleChoiceQuestionParserRuleCall_0() { return cSingleChoiceQuestionParserRuleCall_0; }
		
		//MultipleChoiceQuestion
		public RuleCall getMultipleChoiceQuestionParserRuleCall_1() { return cMultipleChoiceQuestionParserRuleCall_1; }
		
		//TrueFalseQuestion
		public RuleCall getTrueFalseQuestionParserRuleCall_2() { return cTrueFalseQuestionParserRuleCall_2; }
		
		//DescriptiveQuestion
		public RuleCall getDescriptiveQuestionParserRuleCall_3() { return cDescriptiveQuestionParserRuleCall_3; }
	}
	public class SingleChoiceQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.SingleChoiceQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSingle_choiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cScoreAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cScoreINTTerminalRuleCall_4_1_0 = (RuleCall)cScoreAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMediaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cMediaUrlAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cMediaUrlSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cMediaUrlAssignment_5_1.eContents().get(0);
		private final Keyword cOptionsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cOptionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOptionsOptionParserRuleCall_7_0 = (RuleCall)cOptionsAssignment_7.eContents().get(0);
		private final Keyword cCorrectKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCorrectOptionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cCorrectOptionOptionCrossReference_9_0 = (CrossReference)cCorrectOptionAssignment_9.eContents().get(0);
		private final RuleCall cCorrectOptionOptionIDTerminalRuleCall_9_0_1 = (RuleCall)cCorrectOptionOptionCrossReference_9_0.eContents().get(1);
		private final Keyword cEndKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//SingleChoiceQuestion:
		//    'single_choice' name=ID
		//        'text' text=STRING
		//        ('val' score=INT)?
		//        ('media' mediaUrl=STRING)?
		//        'options'
		//            options+=Option+
		//        'correct' correctOption=[Option]
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'single_choice' name=ID
		//    'text' text=STRING
		//    ('val' score=INT)?
		//    ('media' mediaUrl=STRING)?
		//    'options'
		//        options+=Option+
		//    'correct' correctOption=[Option]
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'single_choice'
		public Keyword getSingle_choiceKeyword_0() { return cSingle_choiceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'text'
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }
		
		//text=STRING
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0() { return cTextSTRINGTerminalRuleCall_3_0; }
		
		//('val' score=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'val'
		public Keyword getValKeyword_4_0() { return cValKeyword_4_0; }
		
		//score=INT
		public Assignment getScoreAssignment_4_1() { return cScoreAssignment_4_1; }
		
		//INT
		public RuleCall getScoreINTTerminalRuleCall_4_1_0() { return cScoreINTTerminalRuleCall_4_1_0; }
		
		//('media' mediaUrl=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'media'
		public Keyword getMediaKeyword_5_0() { return cMediaKeyword_5_0; }
		
		//mediaUrl=STRING
		public Assignment getMediaUrlAssignment_5_1() { return cMediaUrlAssignment_5_1; }
		
		//STRING
		public RuleCall getMediaUrlSTRINGTerminalRuleCall_5_1_0() { return cMediaUrlSTRINGTerminalRuleCall_5_1_0; }
		
		//'options'
		public Keyword getOptionsKeyword_6() { return cOptionsKeyword_6; }
		
		//options+=Option+
		public Assignment getOptionsAssignment_7() { return cOptionsAssignment_7; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_7_0() { return cOptionsOptionParserRuleCall_7_0; }
		
		//'correct'
		public Keyword getCorrectKeyword_8() { return cCorrectKeyword_8; }
		
		//correctOption=[Option]
		public Assignment getCorrectOptionAssignment_9() { return cCorrectOptionAssignment_9; }
		
		//[Option]
		public CrossReference getCorrectOptionOptionCrossReference_9_0() { return cCorrectOptionOptionCrossReference_9_0; }
		
		//ID
		public RuleCall getCorrectOptionOptionIDTerminalRuleCall_9_0_1() { return cCorrectOptionOptionIDTerminalRuleCall_9_0_1; }
		
		//'end'
		public Keyword getEndKeyword_10() { return cEndKeyword_10; }
	}
	public class MultipleChoiceQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.MultipleChoiceQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMulti_choiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cScoreAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cScoreINTTerminalRuleCall_4_1_0 = (RuleCall)cScoreAssignment_4_1.eContents().get(0);
		private final Keyword cOptionsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOptionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOptionsOptionParserRuleCall_6_0 = (RuleCall)cOptionsAssignment_6.eContents().get(0);
		private final Keyword cEndKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//MultipleChoiceQuestion:
		//    'multi_choice' name=ID
		//        'text' text=STRING
		//        ('val' score=INT)?
		//        'options'
		//            options+=Option+
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'multi_choice' name=ID
		//    'text' text=STRING
		//    ('val' score=INT)?
		//    'options'
		//        options+=Option+
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'multi_choice'
		public Keyword getMulti_choiceKeyword_0() { return cMulti_choiceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'text'
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }
		
		//text=STRING
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0() { return cTextSTRINGTerminalRuleCall_3_0; }
		
		//('val' score=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'val'
		public Keyword getValKeyword_4_0() { return cValKeyword_4_0; }
		
		//score=INT
		public Assignment getScoreAssignment_4_1() { return cScoreAssignment_4_1; }
		
		//INT
		public RuleCall getScoreINTTerminalRuleCall_4_1_0() { return cScoreINTTerminalRuleCall_4_1_0; }
		
		//'options'
		public Keyword getOptionsKeyword_5() { return cOptionsKeyword_5; }
		
		//options+=Option+
		public Assignment getOptionsAssignment_6() { return cOptionsAssignment_6; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_6_0() { return cOptionsOptionParserRuleCall_6_0; }
		
		//'end'
		public Keyword getEndKeyword_7() { return cEndKeyword_7; }
	}
	public class TrueFalseQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.TrueFalseQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTrue_falseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cScoreAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cScoreINTTerminalRuleCall_4_1_0 = (RuleCall)cScoreAssignment_4_1.eContents().get(0);
		private final Keyword cAnswerKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIsTrueAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIsTrueEBooleanParserRuleCall_6_0 = (RuleCall)cIsTrueAssignment_6.eContents().get(0);
		private final Keyword cEndKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TrueFalseQuestion:
		//    'true_false' name=ID
		//        'text' text=STRING
		//        ('val' score=INT)?
		//        'answer' isTrue=EBoolean
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'true_false' name=ID
		//    'text' text=STRING
		//    ('val' score=INT)?
		//    'answer' isTrue=EBoolean
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'true_false'
		public Keyword getTrue_falseKeyword_0() { return cTrue_falseKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'text'
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }
		
		//text=STRING
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0() { return cTextSTRINGTerminalRuleCall_3_0; }
		
		//('val' score=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'val'
		public Keyword getValKeyword_4_0() { return cValKeyword_4_0; }
		
		//score=INT
		public Assignment getScoreAssignment_4_1() { return cScoreAssignment_4_1; }
		
		//INT
		public RuleCall getScoreINTTerminalRuleCall_4_1_0() { return cScoreINTTerminalRuleCall_4_1_0; }
		
		//'answer'
		public Keyword getAnswerKeyword_5() { return cAnswerKeyword_5; }
		
		//isTrue=EBoolean
		public Assignment getIsTrueAssignment_6() { return cIsTrueAssignment_6; }
		
		//EBoolean
		public RuleCall getIsTrueEBooleanParserRuleCall_6_0() { return cIsTrueEBooleanParserRuleCall_6_0; }
		
		//'end'
		public Keyword getEndKeyword_7() { return cEndKeyword_7; }
	}
	public class DescriptiveQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.DescriptiveQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDescriptiveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cScoreAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cScoreINTTerminalRuleCall_4_1_0 = (RuleCall)cScoreAssignment_4_1.eContents().get(0);
		private final Keyword cEndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DescriptiveQuestion:
		//    'descriptive' name=ID
		//        'text' text=STRING
		//        ('val' score=INT)?
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'descriptive' name=ID
		//    'text' text=STRING
		//    ('val' score=INT)?
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'descriptive'
		public Keyword getDescriptiveKeyword_0() { return cDescriptiveKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'text'
		public Keyword getTextKeyword_2() { return cTextKeyword_2; }
		
		//text=STRING
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0() { return cTextSTRINGTerminalRuleCall_3_0; }
		
		//('val' score=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'val'
		public Keyword getValKeyword_4_0() { return cValKeyword_4_0; }
		
		//score=INT
		public Assignment getScoreAssignment_4_1() { return cScoreAssignment_4_1; }
		
		//INT
		public RuleCall getScoreINTTerminalRuleCall_4_1_0() { return cScoreINTTerminalRuleCall_4_1_0; }
		
		//'end'
		public Keyword getEndKeyword_5() { return cEndKeyword_5; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.Option");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		
		//Option:
		//    name=ID '->' text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '->' text=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_1() { return cHyphenMinusGreaterThanSignKeyword_1; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class QuizResultElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.QuizResult");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResultKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cUserKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUserAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cUserUserCrossReference_3_0 = (CrossReference)cUserAssignment_3.eContents().get(0);
		private final RuleCall cUserUserIDTerminalRuleCall_3_0_1 = (RuleCall)cUserUserCrossReference_3_0.eContents().get(1);
		private final Keyword cQuizKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cQuizAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cQuizQuizCrossReference_5_0 = (CrossReference)cQuizAssignment_5.eContents().get(0);
		private final RuleCall cQuizQuizIDTerminalRuleCall_5_0_1 = (RuleCall)cQuizQuizCrossReference_5_0.eContents().get(1);
		private final Keyword cScoreKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFinalScoreAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFinalScoreINTTerminalRuleCall_7_0 = (RuleCall)cFinalScoreAssignment_7.eContents().get(0);
		private final Keyword cResponsesKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cResponsesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cResponsesUserResponseParserRuleCall_10_0 = (RuleCall)cResponsesAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEndKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//QuizResult:
		//    'result' name=ID
		//        'user' user=[User]
		//        'quiz' quiz=[Quiz]
		//        'score' finalScore=INT
		//        'responses' '{' responses+=UserResponse+ '}'
		//    'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'result' name=ID
		//    'user' user=[User]
		//    'quiz' quiz=[Quiz]
		//    'score' finalScore=INT
		//    'responses' '{' responses+=UserResponse+ '}'
		//'end'
		public Group getGroup() { return cGroup; }
		
		//'result'
		public Keyword getResultKeyword_0() { return cResultKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'user'
		public Keyword getUserKeyword_2() { return cUserKeyword_2; }
		
		//user=[User]
		public Assignment getUserAssignment_3() { return cUserAssignment_3; }
		
		//[User]
		public CrossReference getUserUserCrossReference_3_0() { return cUserUserCrossReference_3_0; }
		
		//ID
		public RuleCall getUserUserIDTerminalRuleCall_3_0_1() { return cUserUserIDTerminalRuleCall_3_0_1; }
		
		//'quiz'
		public Keyword getQuizKeyword_4() { return cQuizKeyword_4; }
		
		//quiz=[Quiz]
		public Assignment getQuizAssignment_5() { return cQuizAssignment_5; }
		
		//[Quiz]
		public CrossReference getQuizQuizCrossReference_5_0() { return cQuizQuizCrossReference_5_0; }
		
		//ID
		public RuleCall getQuizQuizIDTerminalRuleCall_5_0_1() { return cQuizQuizIDTerminalRuleCall_5_0_1; }
		
		//'score'
		public Keyword getScoreKeyword_6() { return cScoreKeyword_6; }
		
		//finalScore=INT
		public Assignment getFinalScoreAssignment_7() { return cFinalScoreAssignment_7; }
		
		//INT
		public RuleCall getFinalScoreINTTerminalRuleCall_7_0() { return cFinalScoreINTTerminalRuleCall_7_0; }
		
		//'responses'
		public Keyword getResponsesKeyword_8() { return cResponsesKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//responses+=UserResponse+
		public Assignment getResponsesAssignment_10() { return cResponsesAssignment_10; }
		
		//UserResponse
		public RuleCall getResponsesUserResponseParserRuleCall_10_0() { return cResponsesUserResponseParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'end'
		public Keyword getEndKeyword_12() { return cEndKeyword_12; }
	}
	public class UserResponseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.UserResponse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQuestionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cQuestionQuestionCrossReference_1_0 = (CrossReference)cQuestionAssignment_1.eContents().get(0);
		private final RuleCall cQuestionQuestionIDTerminalRuleCall_1_0_1 = (RuleCall)cQuestionQuestionCrossReference_1_0.eContents().get(1);
		private final Keyword cProvided_answerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAnswerSTRINGTerminalRuleCall_3_0 = (RuleCall)cAnswerAssignment_3.eContents().get(0);
		private final Keyword cIs_correctKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCorrectAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCorrectEBooleanParserRuleCall_5_0 = (RuleCall)cCorrectAssignment_5.eContents().get(0);
		
		//UserResponse:
		//    'question' question=[Question]
		//    'provided_answer' answer=STRING
		//    'is_correct' correct=EBoolean
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'question' question=[Question]
		//'provided_answer' answer=STRING
		//'is_correct' correct=EBoolean
		public Group getGroup() { return cGroup; }
		
		//'question'
		public Keyword getQuestionKeyword_0() { return cQuestionKeyword_0; }
		
		//question=[Question]
		public Assignment getQuestionAssignment_1() { return cQuestionAssignment_1; }
		
		//[Question]
		public CrossReference getQuestionQuestionCrossReference_1_0() { return cQuestionQuestionCrossReference_1_0; }
		
		//ID
		public RuleCall getQuestionQuestionIDTerminalRuleCall_1_0_1() { return cQuestionQuestionIDTerminalRuleCall_1_0_1; }
		
		//'provided_answer'
		public Keyword getProvided_answerKeyword_2() { return cProvided_answerKeyword_2; }
		
		//answer=STRING
		public Assignment getAnswerAssignment_3() { return cAnswerAssignment_3; }
		
		//STRING
		public RuleCall getAnswerSTRINGTerminalRuleCall_3_0() { return cAnswerSTRINGTerminalRuleCall_3_0; }
		
		//'is_correct'
		public Keyword getIs_correctKeyword_4() { return cIs_correctKeyword_4; }
		
		//correct=EBoolean
		public Assignment getCorrectAssignment_5() { return cCorrectAssignment_5; }
		
		//EBoolean
		public RuleCall getCorrectEBooleanParserRuleCall_5_0() { return cCorrectEBooleanParserRuleCall_5_0; }
	}
	
	public class UserRoleElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.UserRole");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cADMINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cADMINAdminKeyword_0_0 = (Keyword)cADMINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSTUDENTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSTUDENTStudentKeyword_1_0 = (Keyword)cSTUDENTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum UserRole:
		//    ADMIN = 'admin' | STUDENT = 'student';
		public EnumRule getRule() { return rule; }
		
		//ADMIN = 'admin' | STUDENT = 'student'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ADMIN = 'admin'
		public EnumLiteralDeclaration getADMINEnumLiteralDeclaration_0() { return cADMINEnumLiteralDeclaration_0; }
		
		//'admin'
		public Keyword getADMINAdminKeyword_0_0() { return cADMINAdminKeyword_0_0; }
		
		//STUDENT = 'student'
		public EnumLiteralDeclaration getSTUDENTEnumLiteralDeclaration_1() { return cSTUDENTEnumLiteralDeclaration_1; }
		
		//'student'
		public Keyword getSTUDENTStudentKeyword_1_0() { return cSTUDENTStudentKeyword_1_0; }
	}
	public class AccessTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quiz.QuizDSL.AccessType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPUBLICEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPUBLICPublicKeyword_0_0 = (Keyword)cPUBLICEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPRIVATEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPRIVATEPrivateKeyword_1_0 = (Keyword)cPRIVATEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum AccessType:
		//    PUBLIC = 'public' | PRIVATE = 'private';
		public EnumRule getRule() { return rule; }
		
		//PUBLIC = 'public' | PRIVATE = 'private'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PUBLIC = 'public'
		public EnumLiteralDeclaration getPUBLICEnumLiteralDeclaration_0() { return cPUBLICEnumLiteralDeclaration_0; }
		
		//'public'
		public Keyword getPUBLICPublicKeyword_0_0() { return cPUBLICPublicKeyword_0_0; }
		
		//PRIVATE = 'private'
		public EnumLiteralDeclaration getPRIVATEEnumLiteralDeclaration_1() { return cPRIVATEEnumLiteralDeclaration_1; }
		
		//'private'
		public Keyword getPRIVATEPrivateKeyword_1_0() { return cPRIVATEPrivateKeyword_1_0; }
	}
	
	private final QuizGameSystemElements pQuizGameSystem;
	private final ThemeElements pTheme;
	private final UserElements pUser;
	private final UserRoleElements eUserRole;
	private final QuizPlatformElements pQuizPlatform;
	private final QuizElements pQuiz;
	private final QuizConfigElements pQuizConfig;
	private final AccessTypeElements eAccessType;
	private final QuestionElements pQuestion;
	private final SingleChoiceQuestionElements pSingleChoiceQuestion;
	private final MultipleChoiceQuestionElements pMultipleChoiceQuestion;
	private final TrueFalseQuestionElements pTrueFalseQuestion;
	private final DescriptiveQuestionElements pDescriptiveQuestion;
	private final OptionElements pOption;
	private final EBooleanElements pEBoolean;
	private final QuizResultElements pQuizResult;
	private final UserResponseElements pUserResponse;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public QuizDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pQuizGameSystem = new QuizGameSystemElements();
		this.pTheme = new ThemeElements();
		this.pUser = new UserElements();
		this.eUserRole = new UserRoleElements();
		this.pQuizPlatform = new QuizPlatformElements();
		this.pQuiz = new QuizElements();
		this.pQuizConfig = new QuizConfigElements();
		this.eAccessType = new AccessTypeElements();
		this.pQuestion = new QuestionElements();
		this.pSingleChoiceQuestion = new SingleChoiceQuestionElements();
		this.pMultipleChoiceQuestion = new MultipleChoiceQuestionElements();
		this.pTrueFalseQuestion = new TrueFalseQuestionElements();
		this.pDescriptiveQuestion = new DescriptiveQuestionElements();
		this.pOption = new OptionElements();
		this.pEBoolean = new EBooleanElements();
		this.pQuizResult = new QuizResultElements();
		this.pUserResponse = new UserResponseElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.example.quiz.QuizDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//QuizGameSystem:
	//    (themes+=Theme | users+=User | platform=QuizPlatform | results+=QuizResult)*;
	public QuizGameSystemElements getQuizGameSystemAccess() {
		return pQuizGameSystem;
	}
	
	public ParserRule getQuizGameSystemRule() {
		return getQuizGameSystemAccess().getRule();
	}
	
	//Theme:
	//    'theme' name=ID
	//        'primary' primaryColor=STRING
	//        'secondary' secondaryColor=STRING
	//        'bg' backgroundColor=STRING
	//        'text' textColor=STRING
	//        'font' fontName=STRING
	//    'end';
	public ThemeElements getThemeAccess() {
		return pTheme;
	}
	
	public ParserRule getThemeRule() {
		return getThemeAccess().getRule();
	}
	
	//User:
	//    'user' name=ID
	//        'uid' username=STRING
	//        'pwd' password=STRING
	//        'name' fullName=STRING
	//        (role=UserRole)?
	//    'end';
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//enum UserRole:
	//    ADMIN = 'admin' | STUDENT = 'student';
	public UserRoleElements getUserRoleAccess() {
		return eUserRole;
	}
	
	public EnumRule getUserRoleRule() {
		return getUserRoleAccess().getRule();
	}
	
	//QuizPlatform:
	//    'platform' name=ID
	//        'title' title=STRING
	//        'subtitle' subtitle=STRING
	//        'logo' logo=STRING
	//        'use_theme' theme=[Theme]
	//        quizzes+=Quiz*
	//    'end';
	public QuizPlatformElements getQuizPlatformAccess() {
		return pQuizPlatform;
	}
	
	public ParserRule getQuizPlatformRule() {
		return getQuizPlatformAccess().getRule();
	}
	
	//Quiz:
	//    'quiz' name=ID
	//        'label' label=STRING
	//        'desc' description=STRING
	//        'icon' icon=STRING
	//        config=QuizConfig
	//        questions+=Question*
	//    'end';
	public QuizElements getQuizAccess() {
		return pQuiz;
	}
	
	public ParserRule getQuizRule() {
		return getQuizAccess().getRule();
	}
	
	//QuizConfig:
	//    {QuizConfig}
	//    (access=AccessType)
	//    ('time' duration=INT 'min')?
	//    ('start' startTime=STRING)?
	//    ('end' endTime=STRING)?
	//    (shuffleQuestions?='shuffle')?
	//    (showResult?='show_result')?
	//    ('score' totalScore=INT)?;
	public QuizConfigElements getQuizConfigAccess() {
		return pQuizConfig;
	}
	
	public ParserRule getQuizConfigRule() {
		return getQuizConfigAccess().getRule();
	}
	
	//enum AccessType:
	//    PUBLIC = 'public' | PRIVATE = 'private';
	public AccessTypeElements getAccessTypeAccess() {
		return eAccessType;
	}
	
	public EnumRule getAccessTypeRule() {
		return getAccessTypeAccess().getRule();
	}
	
	//Question:
	//    SingleChoiceQuestion | MultipleChoiceQuestion | TrueFalseQuestion | DescriptiveQuestion;
	public QuestionElements getQuestionAccess() {
		return pQuestion;
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}
	
	//SingleChoiceQuestion:
	//    'single_choice' name=ID
	//        'text' text=STRING
	//        ('val' score=INT)?
	//        ('media' mediaUrl=STRING)?
	//        'options'
	//            options+=Option+
	//        'correct' correctOption=[Option]
	//    'end';
	public SingleChoiceQuestionElements getSingleChoiceQuestionAccess() {
		return pSingleChoiceQuestion;
	}
	
	public ParserRule getSingleChoiceQuestionRule() {
		return getSingleChoiceQuestionAccess().getRule();
	}
	
	//MultipleChoiceQuestion:
	//    'multi_choice' name=ID
	//        'text' text=STRING
	//        ('val' score=INT)?
	//        'options'
	//            options+=Option+
	//    'end';
	public MultipleChoiceQuestionElements getMultipleChoiceQuestionAccess() {
		return pMultipleChoiceQuestion;
	}
	
	public ParserRule getMultipleChoiceQuestionRule() {
		return getMultipleChoiceQuestionAccess().getRule();
	}
	
	//TrueFalseQuestion:
	//    'true_false' name=ID
	//        'text' text=STRING
	//        ('val' score=INT)?
	//        'answer' isTrue=EBoolean
	//    'end';
	public TrueFalseQuestionElements getTrueFalseQuestionAccess() {
		return pTrueFalseQuestion;
	}
	
	public ParserRule getTrueFalseQuestionRule() {
		return getTrueFalseQuestionAccess().getRule();
	}
	
	//DescriptiveQuestion:
	//    'descriptive' name=ID
	//        'text' text=STRING
	//        ('val' score=INT)?
	//    'end';
	public DescriptiveQuestionElements getDescriptiveQuestionAccess() {
		return pDescriptiveQuestion;
	}
	
	public ParserRule getDescriptiveQuestionRule() {
		return getDescriptiveQuestionAccess().getRule();
	}
	
	//Option:
	//    name=ID '->' text=STRING;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//QuizResult:
	//    'result' name=ID
	//        'user' user=[User]
	//        'quiz' quiz=[Quiz]
	//        'score' finalScore=INT
	//        'responses' '{' responses+=UserResponse+ '}'
	//    'end';
	public QuizResultElements getQuizResultAccess() {
		return pQuizResult;
	}
	
	public ParserRule getQuizResultRule() {
		return getQuizResultAccess().getRule();
	}
	
	//UserResponse:
	//    'question' question=[Question]
	//    'provided_answer' answer=STRING
	//    'is_correct' correct=EBoolean
	//;
	public UserResponseElements getUserResponseAccess() {
		return pUserResponse;
	}
	
	public ParserRule getUserResponseRule() {
		return getUserResponseAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
