/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quiz Result</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.QuizResult#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizResult#getUser <em>User</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizResult#getQuiz <em>Quiz</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizResult#getFinalScore <em>Final Score</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizResult#getResponses <em>Responses</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult()
 * @model
 * @generated
 */
public interface QuizResult extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizResult#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>User</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>User</em>' reference.
   * @see #setUser(User)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult_User()
   * @model
   * @generated
   */
  User getUser();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizResult#getUser <em>User</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>User</em>' reference.
   * @see #getUser()
   * @generated
   */
  void setUser(User value);

  /**
   * Returns the value of the '<em><b>Quiz</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quiz</em>' reference.
   * @see #setQuiz(Quiz)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult_Quiz()
   * @model
   * @generated
   */
  Quiz getQuiz();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizResult#getQuiz <em>Quiz</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quiz</em>' reference.
   * @see #getQuiz()
   * @generated
   */
  void setQuiz(Quiz value);

  /**
   * Returns the value of the '<em><b>Final Score</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final Score</em>' attribute.
   * @see #setFinalScore(int)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult_FinalScore()
   * @model
   * @generated
   */
  int getFinalScore();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizResult#getFinalScore <em>Final Score</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Final Score</em>' attribute.
   * @see #getFinalScore()
   * @generated
   */
  void setFinalScore(int value);

  /**
   * Returns the value of the '<em><b>Responses</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.UserResponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Responses</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizResult_Responses()
   * @model containment="true"
   * @generated
   */
  EList<UserResponse> getResponses();

} // QuizResult
