/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quiz Platform</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getTitle <em>Title</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getSubtitle <em>Subtitle</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getLogo <em>Logo</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getTheme <em>Theme</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizPlatform#getQuizzes <em>Quizzes</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform()
 * @model
 * @generated
 */
public interface QuizPlatform extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizPlatform#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizPlatform#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Subtitle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subtitle</em>' attribute.
   * @see #setSubtitle(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Subtitle()
   * @model
   * @generated
   */
  String getSubtitle();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizPlatform#getSubtitle <em>Subtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subtitle</em>' attribute.
   * @see #getSubtitle()
   * @generated
   */
  void setSubtitle(String value);

  /**
   * Returns the value of the '<em><b>Logo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logo</em>' attribute.
   * @see #setLogo(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Logo()
   * @model
   * @generated
   */
  String getLogo();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizPlatform#getLogo <em>Logo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logo</em>' attribute.
   * @see #getLogo()
   * @generated
   */
  void setLogo(String value);

  /**
   * Returns the value of the '<em><b>Theme</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Theme</em>' reference.
   * @see #setTheme(Theme)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Theme()
   * @model
   * @generated
   */
  Theme getTheme();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizPlatform#getTheme <em>Theme</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Theme</em>' reference.
   * @see #getTheme()
   * @generated
   */
  void setTheme(Theme value);

  /**
   * Returns the value of the '<em><b>Quizzes</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.Quiz}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quizzes</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizPlatform_Quizzes()
   * @model containment="true"
   * @generated
   */
  EList<Quiz> getQuizzes();

} // QuizPlatform
