/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.example.quiz.quizDSL.QuizDSLPackage
 * @generated
 */
public interface QuizDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QuizDSLFactory eINSTANCE = org.example.quiz.quizDSL.impl.QuizDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Quiz Game System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quiz Game System</em>'.
   * @generated
   */
  QuizGameSystem createQuizGameSystem();

  /**
   * Returns a new object of class '<em>Theme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Theme</em>'.
   * @generated
   */
  Theme createTheme();

  /**
   * Returns a new object of class '<em>User</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User</em>'.
   * @generated
   */
  User createUser();

  /**
   * Returns a new object of class '<em>Quiz Platform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quiz Platform</em>'.
   * @generated
   */
  QuizPlatform createQuizPlatform();

  /**
   * Returns a new object of class '<em>Quiz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quiz</em>'.
   * @generated
   */
  Quiz createQuiz();

  /**
   * Returns a new object of class '<em>Quiz Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quiz Config</em>'.
   * @generated
   */
  QuizConfig createQuizConfig();

  /**
   * Returns a new object of class '<em>Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Question</em>'.
   * @generated
   */
  Question createQuestion();

  /**
   * Returns a new object of class '<em>Single Choice Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Choice Question</em>'.
   * @generated
   */
  SingleChoiceQuestion createSingleChoiceQuestion();

  /**
   * Returns a new object of class '<em>Multiple Choice Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiple Choice Question</em>'.
   * @generated
   */
  MultipleChoiceQuestion createMultipleChoiceQuestion();

  /**
   * Returns a new object of class '<em>True False Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>True False Question</em>'.
   * @generated
   */
  TrueFalseQuestion createTrueFalseQuestion();

  /**
   * Returns a new object of class '<em>Descriptive Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Descriptive Question</em>'.
   * @generated
   */
  DescriptiveQuestion createDescriptiveQuestion();

  /**
   * Returns a new object of class '<em>Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option</em>'.
   * @generated
   */
  Option createOption();

  /**
   * Returns a new object of class '<em>Quiz Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quiz Result</em>'.
   * @generated
   */
  QuizResult createQuizResult();

  /**
   * Returns a new object of class '<em>User Response</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Response</em>'.
   * @generated
   */
  UserResponse createUserResponse();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  QuizDSLPackage getQuizDSLPackage();

} //QuizDSLFactory
