/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Theme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getPrimaryColor <em>Primary Color</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getSecondaryColor <em>Secondary Color</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getBackgroundColor <em>Background Color</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getTextColor <em>Text Color</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.Theme#getFontName <em>Font Name</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme()
 * @model
 * @generated
 */
public interface Theme extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Primary Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Color</em>' attribute.
   * @see #setPrimaryColor(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_PrimaryColor()
   * @model
   * @generated
   */
  String getPrimaryColor();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getPrimaryColor <em>Primary Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Color</em>' attribute.
   * @see #getPrimaryColor()
   * @generated
   */
  void setPrimaryColor(String value);

  /**
   * Returns the value of the '<em><b>Secondary Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secondary Color</em>' attribute.
   * @see #setSecondaryColor(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_SecondaryColor()
   * @model
   * @generated
   */
  String getSecondaryColor();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getSecondaryColor <em>Secondary Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secondary Color</em>' attribute.
   * @see #getSecondaryColor()
   * @generated
   */
  void setSecondaryColor(String value);

  /**
   * Returns the value of the '<em><b>Background Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Background Color</em>' attribute.
   * @see #setBackgroundColor(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_BackgroundColor()
   * @model
   * @generated
   */
  String getBackgroundColor();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getBackgroundColor <em>Background Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Background Color</em>' attribute.
   * @see #getBackgroundColor()
   * @generated
   */
  void setBackgroundColor(String value);

  /**
   * Returns the value of the '<em><b>Text Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Color</em>' attribute.
   * @see #setTextColor(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_TextColor()
   * @model
   * @generated
   */
  String getTextColor();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getTextColor <em>Text Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Color</em>' attribute.
   * @see #getTextColor()
   * @generated
   */
  void setTextColor(String value);

  /**
   * Returns the value of the '<em><b>Font Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Font Name</em>' attribute.
   * @see #setFontName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTheme_FontName()
   * @model
   * @generated
   */
  String getFontName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.Theme#getFontName <em>Font Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Font Name</em>' attribute.
   * @see #getFontName()
   * @generated
   */
  void setFontName(String value);

} // Theme
