/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>True False Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.TrueFalseQuestion#isIsTrue <em>Is True</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getTrueFalseQuestion()
 * @model
 * @generated
 */
public interface TrueFalseQuestion extends Question
{
  /**
   * Returns the value of the '<em><b>Is True</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is True</em>' attribute.
   * @see #setIsTrue(boolean)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getTrueFalseQuestion_IsTrue()
   * @model
   * @generated
   */
  boolean isIsTrue();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.TrueFalseQuestion#isIsTrue <em>Is True</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is True</em>' attribute.
   * @see #isIsTrue()
   * @generated
   */
  void setIsTrue(boolean value);

} // TrueFalseQuestion
