/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Response</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.UserResponse#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.UserResponse#getAnswer <em>Answer</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.UserResponse#isCorrect <em>Correct</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getUserResponse()
 * @model
 * @generated
 */
public interface UserResponse extends EObject
{
  /**
   * Returns the value of the '<em><b>Question</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' reference.
   * @see #setQuestion(Question)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUserResponse_Question()
   * @model
   * @generated
   */
  Question getQuestion();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.UserResponse#getQuestion <em>Question</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Question</em>' reference.
   * @see #getQuestion()
   * @generated
   */
  void setQuestion(Question value);

  /**
   * Returns the value of the '<em><b>Answer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Answer</em>' attribute.
   * @see #setAnswer(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUserResponse_Answer()
   * @model
   * @generated
   */
  String getAnswer();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.UserResponse#getAnswer <em>Answer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Answer</em>' attribute.
   * @see #getAnswer()
   * @generated
   */
  void setAnswer(String value);

  /**
   * Returns the value of the '<em><b>Correct</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correct</em>' attribute.
   * @see #setCorrect(boolean)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUserResponse_Correct()
   * @model
   * @generated
   */
  boolean isCorrect();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.UserResponse#isCorrect <em>Correct</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correct</em>' attribute.
   * @see #isCorrect()
   * @generated
   */
  void setCorrect(boolean value);

} // UserResponse
