/*
 * generated by Xtext 2.41.0
 */
package org.example.quiz.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.quiz.QuizDSLRuntimeModule;
import org.example.quiz.QuizDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QuizDSLIdeSetup extends QuizDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QuizDSLRuntimeModule(), new QuizDSLIdeModule()));
	}
	
}
