/*
 * generated by Xtext 2.41.0
 */
package org.example.quiz.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuizDSLScopeProvider extends DelegatingScopeProvider {
}
