/*
 * generated by Xtext 2.41.0
 */
package org.example.quiz.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.example.quiz.quizDSL.DescriptiveQuestion;
import org.example.quiz.quizDSL.MultipleChoiceQuestion;
import org.example.quiz.quizDSL.Option;
import org.example.quiz.quizDSL.Quiz;
import org.example.quiz.quizDSL.QuizConfig;
import org.example.quiz.quizDSL.QuizDSLPackage;
import org.example.quiz.quizDSL.QuizGameSystem;
import org.example.quiz.quizDSL.QuizPlatform;
import org.example.quiz.quizDSL.QuizResult;
import org.example.quiz.quizDSL.SingleChoiceQuestion;
import org.example.quiz.quizDSL.Theme;
import org.example.quiz.quizDSL.TrueFalseQuestion;
import org.example.quiz.quizDSL.User;
import org.example.quiz.quizDSL.UserResponse;
import org.example.quiz.services.QuizDSLGrammarAccess;

@SuppressWarnings("all")
public class QuizDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private QuizDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == QuizDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case QuizDSLPackage.DESCRIPTIVE_QUESTION:
				sequence_DescriptiveQuestion(context, (DescriptiveQuestion) semanticObject); 
				return; 
			case QuizDSLPackage.MULTIPLE_CHOICE_QUESTION:
				sequence_MultipleChoiceQuestion(context, (MultipleChoiceQuestion) semanticObject); 
				return; 
			case QuizDSLPackage.OPTION:
				sequence_Option(context, (Option) semanticObject); 
				return; 
			case QuizDSLPackage.QUIZ:
				sequence_Quiz(context, (Quiz) semanticObject); 
				return; 
			case QuizDSLPackage.QUIZ_CONFIG:
				sequence_QuizConfig(context, (QuizConfig) semanticObject); 
				return; 
			case QuizDSLPackage.QUIZ_GAME_SYSTEM:
				sequence_QuizGameSystem(context, (QuizGameSystem) semanticObject); 
				return; 
			case QuizDSLPackage.QUIZ_PLATFORM:
				sequence_QuizPlatform(context, (QuizPlatform) semanticObject); 
				return; 
			case QuizDSLPackage.QUIZ_RESULT:
				sequence_QuizResult(context, (QuizResult) semanticObject); 
				return; 
			case QuizDSLPackage.SINGLE_CHOICE_QUESTION:
				sequence_SingleChoiceQuestion(context, (SingleChoiceQuestion) semanticObject); 
				return; 
			case QuizDSLPackage.THEME:
				sequence_Theme(context, (Theme) semanticObject); 
				return; 
			case QuizDSLPackage.TRUE_FALSE_QUESTION:
				sequence_TrueFalseQuestion(context, (TrueFalseQuestion) semanticObject); 
				return; 
			case QuizDSLPackage.USER:
				sequence_User(context, (User) semanticObject); 
				return; 
			case QuizDSLPackage.USER_RESPONSE:
				sequence_UserResponse(context, (UserResponse) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Question returns DescriptiveQuestion
	 *     DescriptiveQuestion returns DescriptiveQuestion
	 *
	 * Constraint:
	 *     (name=ID text=STRING score=INT?)
	 * </pre>
	 */
	protected void sequence_DescriptiveQuestion(ISerializationContext context, DescriptiveQuestion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Question returns MultipleChoiceQuestion
	 *     MultipleChoiceQuestion returns MultipleChoiceQuestion
	 *
	 * Constraint:
	 *     (name=ID text=STRING score=INT? options+=Option+)
	 * </pre>
	 */
	protected void sequence_MultipleChoiceQuestion(ISerializationContext context, MultipleChoiceQuestion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Option returns Option
	 *
	 * Constraint:
	 *     (name=ID text=STRING)
	 * </pre>
	 */
	protected void sequence_Option(ISerializationContext context, Option semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.OPTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.OPTION__NAME));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.OPTION__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.OPTION__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOptionAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getOptionAccess().getTextSTRINGTerminalRuleCall_2_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     QuizConfig returns QuizConfig
	 *
	 * Constraint:
	 *     (
	 *         access=AccessType 
	 *         duration=INT? 
	 *         startTime=STRING? 
	 *         endTime=STRING? 
	 *         shuffleQuestions?='shuffle'? 
	 *         showResult?='show_result'? 
	 *         totalScore=INT?
	 *     )
	 * </pre>
	 */
	protected void sequence_QuizConfig(ISerializationContext context, QuizConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     QuizGameSystem returns QuizGameSystem
	 *
	 * Constraint:
	 *     (themes+=Theme | users+=User | platform=QuizPlatform | results+=QuizResult)+
	 * </pre>
	 */
	protected void sequence_QuizGameSystem(ISerializationContext context, QuizGameSystem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     QuizPlatform returns QuizPlatform
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         title=STRING 
	 *         subtitle=STRING 
	 *         logo=STRING 
	 *         theme=[Theme|ID] 
	 *         quizzes+=Quiz*
	 *     )
	 * </pre>
	 */
	protected void sequence_QuizPlatform(ISerializationContext context, QuizPlatform semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     QuizResult returns QuizResult
	 *
	 * Constraint:
	 *     (name=ID user=[User|ID] quiz=[Quiz|ID] finalScore=INT responses+=UserResponse+)
	 * </pre>
	 */
	protected void sequence_QuizResult(ISerializationContext context, QuizResult semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Quiz returns Quiz
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         label=STRING 
	 *         description=STRING 
	 *         icon=STRING 
	 *         config=QuizConfig 
	 *         questions+=Question*
	 *     )
	 * </pre>
	 */
	protected void sequence_Quiz(ISerializationContext context, Quiz semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Question returns SingleChoiceQuestion
	 *     SingleChoiceQuestion returns SingleChoiceQuestion
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         text=STRING 
	 *         score=INT? 
	 *         mediaUrl=STRING? 
	 *         options+=Option+ 
	 *         correctOption=[Option|ID]
	 *     )
	 * </pre>
	 */
	protected void sequence_SingleChoiceQuestion(ISerializationContext context, SingleChoiceQuestion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Theme returns Theme
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         primaryColor=STRING 
	 *         secondaryColor=STRING 
	 *         backgroundColor=STRING 
	 *         textColor=STRING 
	 *         fontName=STRING
	 *     )
	 * </pre>
	 */
	protected void sequence_Theme(ISerializationContext context, Theme semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__NAME));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__PRIMARY_COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__PRIMARY_COLOR));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__SECONDARY_COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__SECONDARY_COLOR));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__BACKGROUND_COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__BACKGROUND_COLOR));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__TEXT_COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__TEXT_COLOR));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.THEME__FONT_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.THEME__FONT_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getThemeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getThemeAccess().getPrimaryColorSTRINGTerminalRuleCall_3_0(), semanticObject.getPrimaryColor());
		feeder.accept(grammarAccess.getThemeAccess().getSecondaryColorSTRINGTerminalRuleCall_5_0(), semanticObject.getSecondaryColor());
		feeder.accept(grammarAccess.getThemeAccess().getBackgroundColorSTRINGTerminalRuleCall_7_0(), semanticObject.getBackgroundColor());
		feeder.accept(grammarAccess.getThemeAccess().getTextColorSTRINGTerminalRuleCall_9_0(), semanticObject.getTextColor());
		feeder.accept(grammarAccess.getThemeAccess().getFontNameSTRINGTerminalRuleCall_11_0(), semanticObject.getFontName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Question returns TrueFalseQuestion
	 *     TrueFalseQuestion returns TrueFalseQuestion
	 *
	 * Constraint:
	 *     (name=ID text=STRING score=INT? isTrue=EBoolean)
	 * </pre>
	 */
	protected void sequence_TrueFalseQuestion(ISerializationContext context, TrueFalseQuestion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UserResponse returns UserResponse
	 *
	 * Constraint:
	 *     (question=[Question|ID] answer=STRING correct=EBoolean)
	 * </pre>
	 */
	protected void sequence_UserResponse(ISerializationContext context, UserResponse semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__QUESTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__QUESTION));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__ANSWER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__ANSWER));
			if (transientValues.isValueTransient(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__CORRECT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuizDSLPackage.Literals.USER_RESPONSE__CORRECT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUserResponseAccess().getQuestionQuestionIDTerminalRuleCall_1_0_1(), semanticObject.eGet(QuizDSLPackage.Literals.USER_RESPONSE__QUESTION, false));
		feeder.accept(grammarAccess.getUserResponseAccess().getAnswerSTRINGTerminalRuleCall_3_0(), semanticObject.getAnswer());
		feeder.accept(grammarAccess.getUserResponseAccess().getCorrectEBooleanParserRuleCall_5_0(), semanticObject.isCorrect());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     User returns User
	 *
	 * Constraint:
	 *     (name=ID username=STRING password=STRING fullName=STRING role=UserRole?)
	 * </pre>
	 */
	protected void sequence_User(ISerializationContext context, User semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
