/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Descriptive Question</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getDescriptiveQuestion()
 * @model
 * @generated
 */
public interface DescriptiveQuestion extends Question
{
} // DescriptiveQuestion
