/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiple Choice Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.MultipleChoiceQuestion#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getMultipleChoiceQuestion()
 * @model
 * @generated
 */
public interface MultipleChoiceQuestion extends Question
{
  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.Option}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getMultipleChoiceQuestion_Options()
   * @model containment="true"
   * @generated
   */
  EList<Option> getOptions();

} // MultipleChoiceQuestion
