/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quiz Game System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.QuizGameSystem#getThemes <em>Themes</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizGameSystem#getUsers <em>Users</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizGameSystem#getPlatform <em>Platform</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.QuizGameSystem#getResults <em>Results</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizGameSystem()
 * @model
 * @generated
 */
public interface QuizGameSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Themes</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.Theme}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Themes</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizGameSystem_Themes()
   * @model containment="true"
   * @generated
   */
  EList<Theme> getThemes();

  /**
   * Returns the value of the '<em><b>Users</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.User}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Users</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizGameSystem_Users()
   * @model containment="true"
   * @generated
   */
  EList<User> getUsers();

  /**
   * Returns the value of the '<em><b>Platform</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Platform</em>' containment reference.
   * @see #setPlatform(QuizPlatform)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizGameSystem_Platform()
   * @model containment="true"
   * @generated
   */
  QuizPlatform getPlatform();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.QuizGameSystem#getPlatform <em>Platform</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Platform</em>' containment reference.
   * @see #getPlatform()
   * @generated
   */
  void setPlatform(QuizPlatform value);

  /**
   * Returns the value of the '<em><b>Results</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.QuizResult}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Results</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getQuizGameSystem_Results()
   * @model containment="true"
   * @generated
   */
  EList<QuizResult> getResults();

} // QuizGameSystem
