/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Choice Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.SingleChoiceQuestion#getMediaUrl <em>Media Url</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.SingleChoiceQuestion#getOptions <em>Options</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.SingleChoiceQuestion#getCorrectOption <em>Correct Option</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getSingleChoiceQuestion()
 * @model
 * @generated
 */
public interface SingleChoiceQuestion extends Question
{
  /**
   * Returns the value of the '<em><b>Media Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Media Url</em>' attribute.
   * @see #setMediaUrl(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getSingleChoiceQuestion_MediaUrl()
   * @model
   * @generated
   */
  String getMediaUrl();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.SingleChoiceQuestion#getMediaUrl <em>Media Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Media Url</em>' attribute.
   * @see #getMediaUrl()
   * @generated
   */
  void setMediaUrl(String value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quiz.quizDSL.Option}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getSingleChoiceQuestion_Options()
   * @model containment="true"
   * @generated
   */
  EList<Option> getOptions();

  /**
   * Returns the value of the '<em><b>Correct Option</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correct Option</em>' reference.
   * @see #setCorrectOption(Option)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getSingleChoiceQuestion_CorrectOption()
   * @model
   * @generated
   */
  Option getCorrectOption();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.SingleChoiceQuestion#getCorrectOption <em>Correct Option</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correct Option</em>' reference.
   * @see #getCorrectOption()
   * @generated
   */
  void setCorrectOption(Option value);

} // SingleChoiceQuestion
