/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.User#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.User#getUsername <em>Username</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.User#getPassword <em>Password</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.User#getFullName <em>Full Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.User#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser()
 * @model
 * @generated
 */
public interface User extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.User#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Username</em>' attribute.
   * @see #setUsername(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser_Username()
   * @model
   * @generated
   */
  String getUsername();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.User#getUsername <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Username</em>' attribute.
   * @see #getUsername()
   * @generated
   */
  void setUsername(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.User#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

  /**
   * Returns the value of the '<em><b>Full Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Full Name</em>' attribute.
   * @see #setFullName(String)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser_FullName()
   * @model
   * @generated
   */
  String getFullName();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.User#getFullName <em>Full Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Full Name</em>' attribute.
   * @see #getFullName()
   * @generated
   */
  void setFullName(String value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.quiz.quizDSL.UserRole}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see org.example.quiz.quizDSL.UserRole
   * @see #setRole(UserRole)
   * @see org.example.quiz.quizDSL.QuizDSLPackage#getUser_Role()
   * @model
   * @generated
   */
  UserRole getRole();

  /**
   * Sets the value of the '{@link org.example.quiz.quizDSL.User#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see org.example.quiz.quizDSL.UserRole
   * @see #getRole()
   * @generated
   */
  void setRole(UserRole value);

} // User
