/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.example.quiz.quizDSL.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.example.quiz.quizDSL.QuizDSLPackage
 * @generated
 */
public class QuizDSLAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static QuizDSLPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QuizDSLAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = QuizDSLPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuizDSLSwitch<Adapter> modelSwitch =
    new QuizDSLSwitch<Adapter>()
    {
      @Override
      public Adapter caseQuizGameSystem(QuizGameSystem object)
      {
        return createQuizGameSystemAdapter();
      }
      @Override
      public Adapter caseTheme(Theme object)
      {
        return createThemeAdapter();
      }
      @Override
      public Adapter caseUser(User object)
      {
        return createUserAdapter();
      }
      @Override
      public Adapter caseQuizPlatform(QuizPlatform object)
      {
        return createQuizPlatformAdapter();
      }
      @Override
      public Adapter caseQuiz(Quiz object)
      {
        return createQuizAdapter();
      }
      @Override
      public Adapter caseQuizConfig(QuizConfig object)
      {
        return createQuizConfigAdapter();
      }
      @Override
      public Adapter caseQuestion(Question object)
      {
        return createQuestionAdapter();
      }
      @Override
      public Adapter caseSingleChoiceQuestion(SingleChoiceQuestion object)
      {
        return createSingleChoiceQuestionAdapter();
      }
      @Override
      public Adapter caseMultipleChoiceQuestion(MultipleChoiceQuestion object)
      {
        return createMultipleChoiceQuestionAdapter();
      }
      @Override
      public Adapter caseTrueFalseQuestion(TrueFalseQuestion object)
      {
        return createTrueFalseQuestionAdapter();
      }
      @Override
      public Adapter caseDescriptiveQuestion(DescriptiveQuestion object)
      {
        return createDescriptiveQuestionAdapter();
      }
      @Override
      public Adapter caseOption(Option object)
      {
        return createOptionAdapter();
      }
      @Override
      public Adapter caseQuizResult(QuizResult object)
      {
        return createQuizResultAdapter();
      }
      @Override
      public Adapter caseUserResponse(UserResponse object)
      {
        return createUserResponseAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.QuizGameSystem <em>Quiz Game System</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.QuizGameSystem
   * @generated
   */
  public Adapter createQuizGameSystemAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.Theme <em>Theme</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.Theme
   * @generated
   */
  public Adapter createThemeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.User
   * @generated
   */
  public Adapter createUserAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.QuizPlatform <em>Quiz Platform</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.QuizPlatform
   * @generated
   */
  public Adapter createQuizPlatformAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.Quiz <em>Quiz</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.Quiz
   * @generated
   */
  public Adapter createQuizAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.QuizConfig <em>Quiz Config</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.QuizConfig
   * @generated
   */
  public Adapter createQuizConfigAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.Question
   * @generated
   */
  public Adapter createQuestionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.SingleChoiceQuestion <em>Single Choice Question</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.SingleChoiceQuestion
   * @generated
   */
  public Adapter createSingleChoiceQuestionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.MultipleChoiceQuestion <em>Multiple Choice Question</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.MultipleChoiceQuestion
   * @generated
   */
  public Adapter createMultipleChoiceQuestionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.TrueFalseQuestion <em>True False Question</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.TrueFalseQuestion
   * @generated
   */
  public Adapter createTrueFalseQuestionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.DescriptiveQuestion <em>Descriptive Question</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.DescriptiveQuestion
   * @generated
   */
  public Adapter createDescriptiveQuestionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.Option
   * @generated
   */
  public Adapter createOptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.QuizResult <em>Quiz Result</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.QuizResult
   * @generated
   */
  public Adapter createQuizResultAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.example.quiz.quizDSL.UserResponse <em>User Response</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.example.quiz.quizDSL.UserResponse
   * @generated
   */
  public Adapter createUserResponseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //QuizDSLAdapterFactory
