/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.quiz.quizDSL.DescriptiveQuestion;
import org.example.quiz.quizDSL.QuizDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Descriptive Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DescriptiveQuestionImpl extends QuestionImpl implements DescriptiveQuestion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DescriptiveQuestionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuizDSLPackage.Literals.DESCRIPTIVE_QUESTION;
  }

} //DescriptiveQuestionImpl
