/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.quiz.quizDSL.Quiz;
import org.example.quiz.quizDSL.QuizDSLPackage;
import org.example.quiz.quizDSL.QuizResult;
import org.example.quiz.quizDSL.User;
import org.example.quiz.quizDSL.UserResponse;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Quiz Result</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizResultImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizResultImpl#getUser <em>User</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizResultImpl#getQuiz <em>Quiz</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizResultImpl#getFinalScore <em>Final Score</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizResultImpl#getResponses <em>Responses</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QuizResultImpl extends MinimalEObjectImpl.Container implements QuizResult
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getUser() <em>User</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUser()
   * @generated
   * @ordered
   */
  protected User user;

  /**
   * The cached value of the '{@link #getQuiz() <em>Quiz</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuiz()
   * @generated
   * @ordered
   */
  protected Quiz quiz;

  /**
   * The default value of the '{@link #getFinalScore() <em>Final Score</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinalScore()
   * @generated
   * @ordered
   */
  protected static final int FINAL_SCORE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFinalScore() <em>Final Score</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinalScore()
   * @generated
   * @ordered
   */
  protected int finalScore = FINAL_SCORE_EDEFAULT;

  /**
   * The cached value of the '{@link #getResponses() <em>Responses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResponses()
   * @generated
   * @ordered
   */
  protected EList<UserResponse> responses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuizResultImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuizDSLPackage.Literals.QUIZ_RESULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_RESULT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public User getUser()
  {
    if (user != null && user.eIsProxy())
    {
      InternalEObject oldUser = (InternalEObject)user;
      user = (User)eResolveProxy(oldUser);
      if (user != oldUser)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QuizDSLPackage.QUIZ_RESULT__USER, oldUser, user));
      }
    }
    return user;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public User basicGetUser()
  {
    return user;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUser(User newUser)
  {
    User oldUser = user;
    user = newUser;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_RESULT__USER, oldUser, user));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Quiz getQuiz()
  {
    if (quiz != null && quiz.eIsProxy())
    {
      InternalEObject oldQuiz = (InternalEObject)quiz;
      quiz = (Quiz)eResolveProxy(oldQuiz);
      if (quiz != oldQuiz)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QuizDSLPackage.QUIZ_RESULT__QUIZ, oldQuiz, quiz));
      }
    }
    return quiz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Quiz basicGetQuiz()
  {
    return quiz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQuiz(Quiz newQuiz)
  {
    Quiz oldQuiz = quiz;
    quiz = newQuiz;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_RESULT__QUIZ, oldQuiz, quiz));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFinalScore()
  {
    return finalScore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinalScore(int newFinalScore)
  {
    int oldFinalScore = finalScore;
    finalScore = newFinalScore;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_RESULT__FINAL_SCORE, oldFinalScore, finalScore));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UserResponse> getResponses()
  {
    if (responses == null)
    {
      responses = new EObjectContainmentEList<UserResponse>(UserResponse.class, this, QuizDSLPackage.QUIZ_RESULT__RESPONSES);
    }
    return responses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_RESULT__RESPONSES:
        return ((InternalEList<?>)getResponses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_RESULT__NAME:
        return getName();
      case QuizDSLPackage.QUIZ_RESULT__USER:
        if (resolve) return getUser();
        return basicGetUser();
      case QuizDSLPackage.QUIZ_RESULT__QUIZ:
        if (resolve) return getQuiz();
        return basicGetQuiz();
      case QuizDSLPackage.QUIZ_RESULT__FINAL_SCORE:
        return getFinalScore();
      case QuizDSLPackage.QUIZ_RESULT__RESPONSES:
        return getResponses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_RESULT__NAME:
        setName((String)newValue);
        return;
      case QuizDSLPackage.QUIZ_RESULT__USER:
        setUser((User)newValue);
        return;
      case QuizDSLPackage.QUIZ_RESULT__QUIZ:
        setQuiz((Quiz)newValue);
        return;
      case QuizDSLPackage.QUIZ_RESULT__FINAL_SCORE:
        setFinalScore((Integer)newValue);
        return;
      case QuizDSLPackage.QUIZ_RESULT__RESPONSES:
        getResponses().clear();
        getResponses().addAll((Collection<? extends UserResponse>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_RESULT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case QuizDSLPackage.QUIZ_RESULT__USER:
        setUser((User)null);
        return;
      case QuizDSLPackage.QUIZ_RESULT__QUIZ:
        setQuiz((Quiz)null);
        return;
      case QuizDSLPackage.QUIZ_RESULT__FINAL_SCORE:
        setFinalScore(FINAL_SCORE_EDEFAULT);
        return;
      case QuizDSLPackage.QUIZ_RESULT__RESPONSES:
        getResponses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_RESULT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case QuizDSLPackage.QUIZ_RESULT__USER:
        return user != null;
      case QuizDSLPackage.QUIZ_RESULT__QUIZ:
        return quiz != null;
      case QuizDSLPackage.QUIZ_RESULT__FINAL_SCORE:
        return finalScore != FINAL_SCORE_EDEFAULT;
      case QuizDSLPackage.QUIZ_RESULT__RESPONSES:
        return responses != null && !responses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", finalScore: ");
    result.append(finalScore);
    result.append(')');
    return result.toString();
  }

} //QuizResultImpl
