/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.quiz.quizDSL.QuizDSLPackage;
import org.example.quiz.quizDSL.QuizGameSystem;
import org.example.quiz.quizDSL.QuizPlatform;
import org.example.quiz.quizDSL.QuizResult;
import org.example.quiz.quizDSL.Theme;
import org.example.quiz.quizDSL.User;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Quiz Game System</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizGameSystemImpl#getThemes <em>Themes</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizGameSystemImpl#getUsers <em>Users</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizGameSystemImpl#getPlatform <em>Platform</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.QuizGameSystemImpl#getResults <em>Results</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QuizGameSystemImpl extends MinimalEObjectImpl.Container implements QuizGameSystem
{
  /**
   * The cached value of the '{@link #getThemes() <em>Themes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThemes()
   * @generated
   * @ordered
   */
  protected EList<Theme> themes;

  /**
   * The cached value of the '{@link #getUsers() <em>Users</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsers()
   * @generated
   * @ordered
   */
  protected EList<User> users;

  /**
   * The cached value of the '{@link #getPlatform() <em>Platform</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlatform()
   * @generated
   * @ordered
   */
  protected QuizPlatform platform;

  /**
   * The cached value of the '{@link #getResults() <em>Results</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResults()
   * @generated
   * @ordered
   */
  protected EList<QuizResult> results;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuizGameSystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuizDSLPackage.Literals.QUIZ_GAME_SYSTEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Theme> getThemes()
  {
    if (themes == null)
    {
      themes = new EObjectContainmentEList<Theme>(Theme.class, this, QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES);
    }
    return themes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<User> getUsers()
  {
    if (users == null)
    {
      users = new EObjectContainmentEList<User>(User.class, this, QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS);
    }
    return users;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizPlatform getPlatform()
  {
    return platform;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPlatform(QuizPlatform newPlatform, NotificationChain msgs)
  {
    QuizPlatform oldPlatform = platform;
    platform = newPlatform;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM, oldPlatform, newPlatform);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlatform(QuizPlatform newPlatform)
  {
    if (newPlatform != platform)
    {
      NotificationChain msgs = null;
      if (platform != null)
        msgs = ((InternalEObject)platform).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM, null, msgs);
      if (newPlatform != null)
        msgs = ((InternalEObject)newPlatform).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM, null, msgs);
      msgs = basicSetPlatform(newPlatform, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM, newPlatform, newPlatform));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<QuizResult> getResults()
  {
    if (results == null)
    {
      results = new EObjectContainmentEList<QuizResult>(QuizResult.class, this, QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS);
    }
    return results;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES:
        return ((InternalEList<?>)getThemes()).basicRemove(otherEnd, msgs);
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS:
        return ((InternalEList<?>)getUsers()).basicRemove(otherEnd, msgs);
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM:
        return basicSetPlatform(null, msgs);
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS:
        return ((InternalEList<?>)getResults()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES:
        return getThemes();
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS:
        return getUsers();
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM:
        return getPlatform();
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS:
        return getResults();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES:
        getThemes().clear();
        getThemes().addAll((Collection<? extends Theme>)newValue);
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS:
        getUsers().clear();
        getUsers().addAll((Collection<? extends User>)newValue);
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM:
        setPlatform((QuizPlatform)newValue);
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS:
        getResults().clear();
        getResults().addAll((Collection<? extends QuizResult>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES:
        getThemes().clear();
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS:
        getUsers().clear();
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM:
        setPlatform((QuizPlatform)null);
        return;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS:
        getResults().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__THEMES:
        return themes != null && !themes.isEmpty();
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__USERS:
        return users != null && !users.isEmpty();
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__PLATFORM:
        return platform != null;
      case QuizDSLPackage.QUIZ_GAME_SYSTEM__RESULTS:
        return results != null && !results.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //QuizGameSystemImpl
