/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.example.quiz.quizDSL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class QuizDSLFactoryImpl extends EFactoryImpl implements QuizDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static QuizDSLFactory init()
  {
    try
    {
      QuizDSLFactory theQuizDSLFactory = (QuizDSLFactory)EPackage.Registry.INSTANCE.getEFactory(QuizDSLPackage.eNS_URI);
      if (theQuizDSLFactory != null)
      {
        return theQuizDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new QuizDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QuizDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case QuizDSLPackage.QUIZ_GAME_SYSTEM: return createQuizGameSystem();
      case QuizDSLPackage.THEME: return createTheme();
      case QuizDSLPackage.USER: return createUser();
      case QuizDSLPackage.QUIZ_PLATFORM: return createQuizPlatform();
      case QuizDSLPackage.QUIZ: return createQuiz();
      case QuizDSLPackage.QUIZ_CONFIG: return createQuizConfig();
      case QuizDSLPackage.QUESTION: return createQuestion();
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION: return createSingleChoiceQuestion();
      case QuizDSLPackage.MULTIPLE_CHOICE_QUESTION: return createMultipleChoiceQuestion();
      case QuizDSLPackage.TRUE_FALSE_QUESTION: return createTrueFalseQuestion();
      case QuizDSLPackage.DESCRIPTIVE_QUESTION: return createDescriptiveQuestion();
      case QuizDSLPackage.OPTION: return createOption();
      case QuizDSLPackage.QUIZ_RESULT: return createQuizResult();
      case QuizDSLPackage.USER_RESPONSE: return createUserResponse();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case QuizDSLPackage.USER_ROLE:
        return createUserRoleFromString(eDataType, initialValue);
      case QuizDSLPackage.ACCESS_TYPE:
        return createAccessTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case QuizDSLPackage.USER_ROLE:
        return convertUserRoleToString(eDataType, instanceValue);
      case QuizDSLPackage.ACCESS_TYPE:
        return convertAccessTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizGameSystem createQuizGameSystem()
  {
    QuizGameSystemImpl quizGameSystem = new QuizGameSystemImpl();
    return quizGameSystem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Theme createTheme()
  {
    ThemeImpl theme = new ThemeImpl();
    return theme;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public User createUser()
  {
    UserImpl user = new UserImpl();
    return user;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizPlatform createQuizPlatform()
  {
    QuizPlatformImpl quizPlatform = new QuizPlatformImpl();
    return quizPlatform;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Quiz createQuiz()
  {
    QuizImpl quiz = new QuizImpl();
    return quiz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizConfig createQuizConfig()
  {
    QuizConfigImpl quizConfig = new QuizConfigImpl();
    return quizConfig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Question createQuestion()
  {
    QuestionImpl question = new QuestionImpl();
    return question;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SingleChoiceQuestion createSingleChoiceQuestion()
  {
    SingleChoiceQuestionImpl singleChoiceQuestion = new SingleChoiceQuestionImpl();
    return singleChoiceQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultipleChoiceQuestion createMultipleChoiceQuestion()
  {
    MultipleChoiceQuestionImpl multipleChoiceQuestion = new MultipleChoiceQuestionImpl();
    return multipleChoiceQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TrueFalseQuestion createTrueFalseQuestion()
  {
    TrueFalseQuestionImpl trueFalseQuestion = new TrueFalseQuestionImpl();
    return trueFalseQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DescriptiveQuestion createDescriptiveQuestion()
  {
    DescriptiveQuestionImpl descriptiveQuestion = new DescriptiveQuestionImpl();
    return descriptiveQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Option createOption()
  {
    OptionImpl option = new OptionImpl();
    return option;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizResult createQuizResult()
  {
    QuizResultImpl quizResult = new QuizResultImpl();
    return quizResult;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UserResponse createUserResponse()
  {
    UserResponseImpl userResponse = new UserResponseImpl();
    return userResponse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UserRole createUserRoleFromString(EDataType eDataType, String initialValue)
  {
    UserRole result = UserRole.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertUserRoleToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AccessType createAccessTypeFromString(EDataType eDataType, String initialValue)
  {
    AccessType result = AccessType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertAccessTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuizDSLPackage getQuizDSLPackage()
  {
    return (QuizDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static QuizDSLPackage getPackage()
  {
    return QuizDSLPackage.eINSTANCE;
  }

} //QuizDSLFactoryImpl
