/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.quiz.quizDSL.Option;
import org.example.quiz.quizDSL.QuizDSLPackage;
import org.example.quiz.quizDSL.SingleChoiceQuestion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Choice Question</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.impl.SingleChoiceQuestionImpl#getMediaUrl <em>Media Url</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.SingleChoiceQuestionImpl#getOptions <em>Options</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.SingleChoiceQuestionImpl#getCorrectOption <em>Correct Option</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleChoiceQuestionImpl extends QuestionImpl implements SingleChoiceQuestion
{
  /**
   * The default value of the '{@link #getMediaUrl() <em>Media Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMediaUrl()
   * @generated
   * @ordered
   */
  protected static final String MEDIA_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMediaUrl() <em>Media Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMediaUrl()
   * @generated
   * @ordered
   */
  protected String mediaUrl = MEDIA_URL_EDEFAULT;

  /**
   * The cached value of the '{@link #getOptions() <em>Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptions()
   * @generated
   * @ordered
   */
  protected EList<Option> options;

  /**
   * The cached value of the '{@link #getCorrectOption() <em>Correct Option</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorrectOption()
   * @generated
   * @ordered
   */
  protected Option correctOption;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleChoiceQuestionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuizDSLPackage.Literals.SINGLE_CHOICE_QUESTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMediaUrl()
  {
    return mediaUrl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMediaUrl(String newMediaUrl)
  {
    String oldMediaUrl = mediaUrl;
    mediaUrl = newMediaUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.SINGLE_CHOICE_QUESTION__MEDIA_URL, oldMediaUrl, mediaUrl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Option> getOptions()
  {
    if (options == null)
    {
      options = new EObjectContainmentEList<Option>(Option.class, this, QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS);
    }
    return options;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Option getCorrectOption()
  {
    if (correctOption != null && correctOption.eIsProxy())
    {
      InternalEObject oldCorrectOption = (InternalEObject)correctOption;
      correctOption = (Option)eResolveProxy(oldCorrectOption);
      if (correctOption != oldCorrectOption)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION, oldCorrectOption, correctOption));
      }
    }
    return correctOption;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Option basicGetCorrectOption()
  {
    return correctOption;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCorrectOption(Option newCorrectOption)
  {
    Option oldCorrectOption = correctOption;
    correctOption = newCorrectOption;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION, oldCorrectOption, correctOption));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS:
        return ((InternalEList<?>)getOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__MEDIA_URL:
        return getMediaUrl();
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS:
        return getOptions();
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION:
        if (resolve) return getCorrectOption();
        return basicGetCorrectOption();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__MEDIA_URL:
        setMediaUrl((String)newValue);
        return;
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS:
        getOptions().clear();
        getOptions().addAll((Collection<? extends Option>)newValue);
        return;
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION:
        setCorrectOption((Option)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__MEDIA_URL:
        setMediaUrl(MEDIA_URL_EDEFAULT);
        return;
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS:
        getOptions().clear();
        return;
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION:
        setCorrectOption((Option)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__MEDIA_URL:
        return MEDIA_URL_EDEFAULT == null ? mediaUrl != null : !MEDIA_URL_EDEFAULT.equals(mediaUrl);
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__OPTIONS:
        return options != null && !options.isEmpty();
      case QuizDSLPackage.SINGLE_CHOICE_QUESTION__CORRECT_OPTION:
        return correctOption != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (mediaUrl: ");
    result.append(mediaUrl);
    result.append(')');
    return result.toString();
  }

} //SingleChoiceQuestionImpl
