/**
 * generated by Xtext 2.41.0
 */
package org.example.quiz.quizDSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.quiz.quizDSL.Question;
import org.example.quiz.quizDSL.QuizDSLPackage;
import org.example.quiz.quizDSL.UserResponse;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>User Response</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.quiz.quizDSL.impl.UserResponseImpl#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.UserResponseImpl#getAnswer <em>Answer</em>}</li>
 *   <li>{@link org.example.quiz.quizDSL.impl.UserResponseImpl#isCorrect <em>Correct</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UserResponseImpl extends MinimalEObjectImpl.Container implements UserResponse
{
  /**
   * The cached value of the '{@link #getQuestion() <em>Question</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuestion()
   * @generated
   * @ordered
   */
  protected Question question;

  /**
   * The default value of the '{@link #getAnswer() <em>Answer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnswer()
   * @generated
   * @ordered
   */
  protected static final String ANSWER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAnswer() <em>Answer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnswer()
   * @generated
   * @ordered
   */
  protected String answer = ANSWER_EDEFAULT;

  /**
   * The default value of the '{@link #isCorrect() <em>Correct</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCorrect()
   * @generated
   * @ordered
   */
  protected static final boolean CORRECT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCorrect() <em>Correct</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCorrect()
   * @generated
   * @ordered
   */
  protected boolean correct = CORRECT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UserResponseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuizDSLPackage.Literals.USER_RESPONSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Question getQuestion()
  {
    if (question != null && question.eIsProxy())
    {
      InternalEObject oldQuestion = (InternalEObject)question;
      question = (Question)eResolveProxy(oldQuestion);
      if (question != oldQuestion)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QuizDSLPackage.USER_RESPONSE__QUESTION, oldQuestion, question));
      }
    }
    return question;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Question basicGetQuestion()
  {
    return question;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQuestion(Question newQuestion)
  {
    Question oldQuestion = question;
    question = newQuestion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.USER_RESPONSE__QUESTION, oldQuestion, question));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAnswer()
  {
    return answer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAnswer(String newAnswer)
  {
    String oldAnswer = answer;
    answer = newAnswer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.USER_RESPONSE__ANSWER, oldAnswer, answer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCorrect()
  {
    return correct;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCorrect(boolean newCorrect)
  {
    boolean oldCorrect = correct;
    correct = newCorrect;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuizDSLPackage.USER_RESPONSE__CORRECT, oldCorrect, correct));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuizDSLPackage.USER_RESPONSE__QUESTION:
        if (resolve) return getQuestion();
        return basicGetQuestion();
      case QuizDSLPackage.USER_RESPONSE__ANSWER:
        return getAnswer();
      case QuizDSLPackage.USER_RESPONSE__CORRECT:
        return isCorrect();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuizDSLPackage.USER_RESPONSE__QUESTION:
        setQuestion((Question)newValue);
        return;
      case QuizDSLPackage.USER_RESPONSE__ANSWER:
        setAnswer((String)newValue);
        return;
      case QuizDSLPackage.USER_RESPONSE__CORRECT:
        setCorrect((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.USER_RESPONSE__QUESTION:
        setQuestion((Question)null);
        return;
      case QuizDSLPackage.USER_RESPONSE__ANSWER:
        setAnswer(ANSWER_EDEFAULT);
        return;
      case QuizDSLPackage.USER_RESPONSE__CORRECT:
        setCorrect(CORRECT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuizDSLPackage.USER_RESPONSE__QUESTION:
        return question != null;
      case QuizDSLPackage.USER_RESPONSE__ANSWER:
        return ANSWER_EDEFAULT == null ? answer != null : !ANSWER_EDEFAULT.equals(answer);
      case QuizDSLPackage.USER_RESPONSE__CORRECT:
        return correct != CORRECT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (answer: ");
    result.append(answer);
    result.append(", correct: ");
    result.append(correct);
    result.append(')');
    return result.toString();
  }

} //UserResponseImpl
